### ISSUE TITLE
Remeber user name

### ISSUE THREAD

**Issue by cljoly** [AndrewBelt/hack.chat#1]
Each time the user enters in a new room, he must enter his user name.

It may be stored in localStorage to avoid it.

**Comment by tracker1** [comment]
I was coming to make the same request. was thinking a cookie, but local storage would work too... along with support for `/nick` command to change your nickname.

**Comment by cljoly** [comment]
A `nick` command seems to be a good idee!

**Comment by AndrewBelt** [comment]
Does f1277b6eca42b92d842d27c3582ae0a45a987a5e fix this? New page loads will prompt for the nickname, but the previously used nickname will be filled in inside the prompt box.

**Comment by cljoly** [comment]
@AndrewBelt f1277b6 fix this, thanks.
