### ISSUE TITLE
/channel command

### ISSUE THREAD

**Issue by tracker1** [AndrewBelt/hack.chat#10]
ex... `/channel lobby` would do a `location.replace('/?' + input)`

Also, per #1 `/nick` would be useful.

**Comment by AndrewBelt** [comment]
I'm hesitant to enable commands, since it complicates the system and requires extensive user documentation. I feel it would be an avalanche to just supporting all of IRC commands.

**Comment by tracker1** [comment]
While I understand that... `/channel x` could just redirect to `/?x` .. which would reload the page... in combination with remembering the person's username (via cookie or localstorage) it wouldn't be very annoying... I think just `/channel` and `/nick` should be enough (thought `/msg` would be cool too).
