### ISSUE TITLE
prompt to choose a name wont appear

### ISSUE THREAD

**Issue by the-ashh** [AndrewBelt/hack.chat#106]
im running a website that i want to run hack.chat, but when i go to a server, the prompt to login wont appear. if you want to see, cooler9711.com:8081/?server

**Comment by AndrewBelt** [comment]
The web console says "Firefox can’t establish a connection to the server at ws://cooler9711.com:6060/."

Your websocket server is not up.

**Comment by the-ashh** [comment]
is there a guide on how to set up my websocket server?

**Comment by M4GNV5** [comment]
> ### Server
> 
> node v0.12 or higher is required to run the server.
> - `git clone https://github.com/AndrewBelt/hack.chat.git`
> - `cd hack.chat`
> - `npm install`
> - Copy `config-sample.json` to `config.json` and edit if needed.
> - `npm start` or `node server.js`

\- https://github.com/AndrewBelt/hack.chat#server

**Comment by the-ashh** [comment]
@M4GNV5 ive done that

**Comment by M4GNV5** [comment]
by doing `node server.js` you start your server. What is the output of that?

**Comment by the-ashh** [comment]
![img_3155](https://cloud.githubusercontent.com/assets/16909054/20486650/c24cd89a-afbd-11e6-97ac-7b9229c253c0.PNG)
When I go to my website, it says not implemented.
If you want to see it, the site will be up for awhile.

**Comment by AndrewBelt** [comment]
"Not implemented" means the WebSocket server is successfully running at that address. You just can't view it because it's not serving anything on HTTP. Either change the source code of the client to point to port 8080, or change the WebSocket port to 6060 in the server config.

**Comment by the-ashh** [comment]
@AndrewBelt @M4GNV5 thank you guys for your help. I finally got it up and running!
