### ISSUE TITLE
Logging in?

### ISSUE THREAD

**Issue by k0nsl** [AndrewBelt/hack.chat#108]
I got it all up and running fine with no issues except for one, but its probably just my own stupidity in this case.
How am I supposed to login as the admin? Whenever I try, it just tells me that it isn't possible to impersonate the admin. One more thing, what are some of the mod trip codes?

Thanks in advance.

**Comment by AndrewBelt** [comment]
Your nickname should be followed by a # sign and your tripcode password. e.g. `AzureDiamond#hunter2`.

You can add mod tripcodes to the `mods` key in the config.json file.
