### ISSUE TITLE
Stop others from embedding hack as iframes

### ISSUE THREAD

**Issue by 0x17de** [AndrewBelt/hack.chat#109]
Since users can now login via #something on the url it can be used to spam through iframes.
Some header should be sent while presenting the site:
http://stackoverflow.com/questions/4419883/how-to-forbid-framing#4419925
Also for websockets check the Origin of the socket to be from hack.
For 3rd party libraries they could spoof it (thats okay) but not from other websites through the browser.

**Comment by M4GNV5** [comment]
*cough* JQuery did this *cough*

**Comment by AndrewBelt** [comment]
I was thinking of removing the # feature, but I think it's better than iframes anyway because of the annoying prompt() that happens upon page load. I'll do this in a second.

**Comment by AndrewBelt** [comment]
Fixed. If someone could test this, I'll close the issue.

**Comment by 0x17de** [comment]
@AndrewBelt the frame issue is solved. will the websocket server still accept connections from every Origin?

**Comment by AndrewBelt** [comment]
Yes, I didn't touch the websocket server, but let me know if there are problems.
