### ISSUE TITLE
Client ERR

### ISSUE THREAD

**Issue by HatterTheMadd** [AndrewBelt/hack.chat#120]
Your site is not loading up anymore and we are having a similar problem that you are at the current time. The problemof the client not authenticating. I've talked a bit with Pert and Rut trying to solve this.. We are getting close but to no avail. Anything you could help us with would be greatly appreciated. We can give you our config files. We have a newish security team that are trying to make this secure. But there's a problem. Our guys got it to https, but it breaks the auth because of an unsecured script, i.e. websocket via 6060..
![error](https://cloud.githubusercontent.com/assets/25492218/23320772/528c54f0-fa99-11e6-8e3d-d78d155544a8.PNG)

**Comment by ghost** [comment]
i've been having the same problem tbhf

**Comment by AndrewBelt** [comment]
This should be fixed as of 6+ hours ago. I've been traveling, so Internet is spotty for me. Can you confirm you're not able to connect?

**Comment by ghost** [comment]
connect to hack.chat or my own instance on https?

**Comment by AndrewBelt** [comment]
The original issue was about hack.chat being down.

**Comment by ghost** [comment]
o-oh

yeah its up
