### ISSUE TITLE
$ make bash: make: command not found

### ISSUE THREAD

**Issue by hajing** [AndrewBelt/hack.chat#124]
Hello, I was in the deployment of a problem encountered: how do I use the Windows platform "make" statement?
Client
*cd client
*npm install -g less jade http-server
*make                            <--This step  ： git bash: make: command not found
*http-server

**Comment by AndrewBelt** [comment]
For Windows, you can just run the commands in the Makefile sequentially, which currently happen to be

```bash
mkdir -p schemes
lessc --global-var='name=nese' scheme.less > schemes/nese.css
lessc --global-var='name=mocha' scheme.less > schemes/mocha.css
lessc --global-var='name=default' scheme.less > schemes/default.css
lessc --global-var='name=atelier-lakeside' scheme.less > schemes/atelier-lakeside.css
lessc --global-var='name=ocean' scheme.less > schemes/ocean.css
lessc --global-var='name=atelier-heath' scheme.less > schemes/atelier-heath.css
lessc --global-var='name=bright' scheme.less > schemes/bright.css
lessc --global-var='name=tomorrow' scheme.less > schemes/tomorrow.css
lessc --global-var='name=android' scheme.less > schemes/android.css
lessc --global-var='name=eighties' scheme.less > schemes/eighties.css
lessc --global-var='name=railscasts' scheme.less > schemes/railscasts.css
lessc --global-var='name=greenscreen' scheme.less > schemes/greenscreen.css
lessc --global-var='name=pop' scheme.less > schemes/pop.css
lessc --global-var='name=atelier-seaside' scheme.less > schemes/atelier-seaside.css
lessc --global-var='name=solarized' scheme.less > schemes/solarized.css
lessc --global-var='name=atelier-forest' scheme.less > schemes/atelier-forest.css
lessc --global-var='name=monokai' scheme.less > schemes/monokai.css
lessc --global-var='name=atelier-dune' scheme.less > schemes/atelier-dune.css
lessc --global-var='name=chalk' scheme.less > schemes/chalk.css
jade index.jade
lessc style.less > style.css
```

**Comment by hajing** [comment]
Is to hack.chat \ client folder inside the Makefile file copy to git-bash implementation, such as the first sentence is "SCHEMES_BASE16 = $ (wildcard base16 / *. Less)", I direct Copy to gitbash and then enter it? I am a novice, I hope you can tell me in detail, thank you very much, I am a Chinese, very very like hack.chat.

**Comment by AndrewBelt** [comment]
Just run the above commands within `client/` and it will have the same effect as the Makefile.

**Comment by hajing** [comment]
Thank you very much, I have successfully deployed, thank you again. I will tell my friend about your project, hack.chat is really great!
