### ISSUE TITLE
How to have TbotT on my channel?

### ISSUE THREAD

**Issue by johncentrus** [AndrewBelt/hack.chat#125]
How to have TbotT on my channel?

**Comment by M4GNV5** [comment]
TbotT is a custom client that connects to hack.chat like any other user.

If you want it in a Hack.chat channel i can host it for you. Just tell me the channel name. (I am `cronuS M4GNV5` in [?programming](https://hack.chat/?programming)

Or you can host it youself. Its code can be found [here](https://github.com/M4GNV5/Hack.ChatBot)
For installing & running it do something like
```bash
git clone https://github.com/M4GNV5/Hack.ChatBot
cd Hack.ChatBot
npm install
node ./src/main.js
```

@AndrewBelt Not sure if this my comment is OK with you, as its kinda self-advertising.

**Comment by raf924** [comment]
@johncentrus do it on your own fork

**Comment by johncentrus** [comment]
M4GNV5, My channel is hack.chat/?centrus

**Comment by johncentrus** [comment]
M4GNV5, Do not you mind hosting the bot on my channel?

**Comment by stamsarger** [comment]
The channel has no one on you tard

**Comment by kikada** [comment]
I am in ?DARK-CHAT

**Comment by kikada** [comment]
(I am cronuS M4GNV5 in ?DARK-CHAT

**Comment by M4GNV5** [comment]
dafuq,
1. the channel is empty
2. thats my trip

**Comment by raf924** [comment]
I like that he put thumbs up on his own comments

**Comment by kikada** [comment]
Sorry M4GNV5. Now ?DARK-CHAT  isn't empty.
I will be happy if you host a TbotT in my channel.
I am in ?DARK-CHAT

**Comment by kikada** [comment]
dear M4GNV5, if you can, please wright in TbotT in my channel that programmer is KIKADA6602 an if you can change TbotT name to KIK_ROBOT please

**Comment by raf924** [comment]
Dude do it yourself
