### ISSUE TITLE
Is the stats() command exposed to every user on purpose?

### ISSUE THREAD

**Issue by jhrmnn** [AndrewBelt/hack.chat#128]
At this point, anyone can get the stats by running `send({'cmd': 'stats'})` in the JS browser console.

**Comment by AndrewBelt** [comment]
Yes, some members like recording statistics of people online, and I don't see a problem, as it doesn't expose anyone's information.

**Comment by M4GNV5** [comment]
also feel free to check out https://m4gnus.de/hackchat.html
