### ISSUE TITLE
Overflow still present

### ISSUE THREAD

**Issue by wwandrew** [AndrewBelt/hack.chat#131]
It is still possible to cause the hack.chat server to restart.

**Comment by AndrewBelt** [comment]
It's probably overflowing in the read call, since the node ws library I'm using doesn't have a way to buffer input streams. But if it's fixed on your development server but not in hack.chat, maybe I didn't upgrade the production server correctly.

**Comment by wwandrew** [comment]
I suspected that you may have just not updated it correctly, it happens.
