### ISSUE TITLE
Commands confusion 

### ISSUE THREAD

**Issue by Xfeature** [AndrewBelt/hack.chat#141]
Hi, 

I've only just started playing around with hack.chat **(very nice by the way, massive well done all)**

Do you have a list of commands that can be run and how to run them please.

I noticed that you can login as admin with admin#passwd but have no idea what this enables.

**Comment by AndrewBelt** [comment]
https://github.com/AndrewBelt/hack.chat/blob/master/server.js#L148 here is a comprehensive list of commands.

**Comment by Xfeature** [comment]
Thank you so much for the quick reply, once again great simple chat :) x

**Comment by Xfeature** [comment]
sorry i see the commands section but how do you run them? ....
in the browser window or server side?
i tried  running `:stats`  etc but it didnt work and im logged into a chat as admin

**Comment by AndrewBelt** [comment]
You run them in the browser. If you are admin, for example, you can broadcast a message by opening the web terminal (Ctrl+Shift+K I think?) and typing

    send({cmd: 'broadcast', text: 'Hello world'})

Or you can ban with `send({cmd: 'ban', nick: 'someone'})`

**Comment by Xfeature** [comment]
ok I just used `send({cmd; 'stats'})`

its works :D 

yep it was 

> Ctrl + Shift + K

 in chrome
