### ISSUE TITLE
Server not working | Upgrade Required

### ISSUE THREAD

**Issue by MatteoChesi** [AndrewBelt/hack.chat#146]
Client is up and working but the server is not working 

curl localhost:6060
  Upgrade Required

what version of node i can upgrade to ?

[npm-debug.log](https://github.com/AndrewBelt/hack.chat/files/1523260/npm-debug.log)

**Comment by AndrewBelt** [comment]
That means it's working. (The websocket server that is.) You're just trying to access it with a web browser.

**Comment by raf924** [comment]
Literally the same issue, down to the title, as https://github.com/AndrewBelt/hack.chat/issues/126. Github's issue display could be better.
