### ISSUE TITLE
Hack.chat alternative

### ISSUE THREAD

**Issue by heapoverride** [AndrewBelt/hack.chat#154]
I started this project after hack.chat has been encountering some DDoS attacks and downtime, and now when Andrew Belt completely stopped hosting it i decided to let him and others know about my alternative client/server.

URL: https://vps.unrealsecurity.net/?leet
(websocket url: wss://vps.unrealsecurity.net/chat-ws)

Some already existing features for everyone...
- bbcodes
- code highlighting
- file upload
- images
- desktop notifications

Global/channel admins/mods are able to temporarily block joining from Tor addresses.

Users are able to claim channels that are not yet claimed by anyone else and they will be able to ban/kick people from channels they own. (ban/kick also closes the websocket connection)

Everyone can suggest new features.

/!\ If you are from India, Indonesia, Iran, Iraq, Nigeria, UAE, Turkey, China or Russia and can't speak english (or can't speak at all) please do not join. It was meant to be sarcastic but... please don't.

**Comment by UnrealSecurity** [comment]
Forgot to mention that global/channel admins/mods are able to temporarily block joining from Tor addresses.

**Comment by M4GNV5** [comment]
It's not a real fork when the source is not available. Or maybe it is? At least the front page https://vps.unrealsecurity.net states:
> Server and web client released under the GNU General Public License.

but i can't find it anywhere.

also:

> /!\ If you are from India, Indonesia, Iran, Iraq, Nigeria, UAE, Turkey, China or Russia and can't speak english (or can't speak at all) please do not join. It was meant to be sarcastic but... please don't.

i smell slight racism in here.

**Comment by AndrewBelt** [comment]
My biggest GitHub gripe is that project maintainers can't delete issues, so I'll just close.
