### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by ravensorrow** [AndrewBelt/hack.chat#18]
It should be noted that on Debian/Ubuntu based distributions that the packages npm, nodejs and nodejs-legacy are required to build hack.chat (after cloning).

**Comment by ravensorrow** [comment]
I've also noticed that the following happens after building on my Ubuntu VPS Webserver; (I couldn't post a new issue, it wouldn't let me).

ubuntu@ip-172-31-0-10:/some/path/hack.chat$ npm start

> hack.chat@1.0.0 start /some/path/hack.chat
> node server.js

/some/path/hack.chat/server.js:46
        for (var client of server.clients) {
                        ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
ubuntu@ip-172-31-0-10:/some/path/hack.chat$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
ubuntu@ip-172-31-0-10:/some/path/hack.chat$

**Comment by AndrewBelt** [comment]
node v0.12.0 or higher is required. I'll mention it in the README.

**Comment by ravensorrow** [comment]
Sorry for the late reply, crazy work hours and 2 desktop crashes in the last 2 weeks. Ubuntu 14.04.2 LTS only has a nodejs version of 0.10.25 as the latest, is v0.12.0 a beta?

**Comment by kipukun** [comment]
I would say get the binary directly from NodeJS. It just won't be added by your package manager, but that's fine.

**Comment by ravensorrow** [comment]
From NodeJS's website ( https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories ):

# Note the new setup script name for Node.js v0.12

curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

# Then install with:

sudo apt-get install -y nodejs

**Comment by AndrewBelt** [comment]
Or just download the appropriate binaries here (https://nodejs.org/download/) and run it from the /bin directory. Or compile from the source archive. Or use the Debian or Ubuntu backport repo, which has Node v0.12.
