### ISSUE TITLE
No way to set bots to be ignored by rate limiter

### ISSUE THREAD

**Issue by Inferno42** [AndrewBelt/hack.chat#2]
The most I can get out of hackbot before the rate-limiter kicks in is usually 3 lines or so. Possibly add some form of password verification for users to secure names (Like that of bots) and remove rate limits for those users.

**Comment by Inferno42** [comment]
Also, IP limiting should be either brought up to 2 (So bot devs can work) or have pre-registered bots not count towards the IP limit

**Comment by AndrewBelt** [comment]
Bots should have the same rates as everyone else, since they too can get spammy at times.

**Comment by M4GNV5** [comment]
i know the problems @Inferno42 had and i think the balancing of the police system is a bit unbalanced. Getting only lim -> 1+ for writing a 1 char message but 3 for joining a channel doesnt prevent people from spamming only from joining the channel multiple times
anyhow the only ones who get affected by the 3!! points you get from joining a channel are bots when they have some auth system using invites :disappointed:
