### ISSUE TITLE
Restricted Markdown

### ISSUE THREAD

**Issue by fnky** [AndrewBelt/hack.chat#27]
Some restricted markdown formatting would allow messages with **bold**, _emphasized_ and a few more:
- Code blocks with syntax highlighting
  `js
  var example = require('example');
  `
- Inline code blocks (`example`)

and a few more, whereas a subset of the markdown syntax is restricted:
- Title cases (#)
- Tables (perhaps a feature too for mathematical illustration?)
- Images (would be cool though)

**Comment by WebFreak001** [comment]
+1, but only for code. Bold, etc. could be very distracting and hack.chat is advertising itself as not distracting. Also you have LaTeX already where you can make all the cool math equations

**Comment by fnky** [comment]
I see what you mean, however I feel that bold and cursive text could give more meaning/emphasis to conversations.

**Comment by kipukun** [comment]
You can make things bold and emphasized in LaTeX with:
`\textbf{}`
`\textit{}`
Respectively. I say add that functionality instead of adding a whole 'nother language.

**Comment by WebFreak001** [comment]
textbf and textit doesn't work on hack.chat

**Comment by kipukun** [comment]
I'm saying add that functionality instead of adding MD, since we already have a form of *TeX already.

**Comment by AndrewBelt** [comment]
`\textbf` and `\textit` are not supported by KaTeX, which is reasonable since the project aims to place math on HTML pages rather than rendering complete LaTeX documents in HTML.

Text formatting is not really in the scope of what hack.chat is designed to do, so I'm going to close this issue.

**Comment by wyattjoh** [comment]
I think the best feature that applications like Slack have is when you've entered a triple back tick (```) that when you press enter, it does not submit the chat immediately. While I agree that keeping things simple would prevent the addition of a restricted subset of markdown, I believe the addition of a "do not submit when enter is pressed" checkbox and corresponding "send" button for chat messages would help developers write small code snippets in the chat window without fear that it would submit their partially written code block when the press enter to go to a new line.

**Comment by melon3r** [comment]
You can use Shift+Enter to insert a newline without sending the message.
