### ISSUE TITLE
Install on Synology

### ISSUE THREAD

**Issue by Zorgonaute84** [AndrewBelt/hack.chat#42]
First, thanks for your Hack Chat !

Is it possible to install this on NAS Synology ? I already installed node.js on the nas, but I don't what I have to do next.

Thanks

**Comment by ghost** [comment]
Not really the right place to ask this IMO, but if you have access to bash or something like it, just follow the instructions on the README.

**Comment by AndrewBelt** [comment]
Yup, if you can SSH in and install Node.js, you're almost there. Read the README, and make sure you're using Node 0.12 or higher. Closing for now.
