### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by josdmyer** [AndrewBelt/hack.chat#45]
I'm trying to install hack.chat on a ubuntu 14.04 vm and I can't seem to get it to work.  I have installed git, curl, npm, nodejs, and nodes-legacy.

when I run npm start I get this

> hack.chat@1.0.0 start /root/hack.chat
> node server.js

/root/hack.chat/server.js:60
    for (var client of server.clients) {
                    ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by maxerize** [comment]
Did you run `npm install`?

**Comment by josdmyer** [comment]
I created a new ubuntu 14.04 vm

history

```
2  sudo apt-get install npm nodejs nodejs-legacy

3  sudo apt-get install build-essential libssl-dev

4  sudo apt-get update && sudo apt-get upgrade

5  sudo apt-get install git curl

6  git clone https://github.com/AndrewBelt/hack.chat.git

7  cd hack.chat

8  sudo npm install

9  cp config-sample.json config.json
```

   10  vim config.json

   11  sudo npm start

sudo npm install

> utf-8-validate@1.1.0 install
> /home/josdmyer/hack.chat/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild
> 
> bufferutil@1.1.0 install
> /home/josdmyer/hack.chat/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory
`/home/josdmyer/hack.chat/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
make: Entering directory
`/home/josdmyer/hack.chat/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory
`/home/josdmyer/hack.chat/node_modules/ws/node_modules/utf-8-validate/build'
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory
`/home/josdmyer/hack.chat/node_modules/ws/node_modules/bufferutil/build'
ws@0.7.2 node_modules/ws
├── options@0.0.6
├── ultron@1.0.2
├── utf-8-validate@1.1.0 (bindings@1.2.1, nan@1.8.4)
└── bufferutil@1.1.0 (bindings@1.2.1, nan@1.8.4)

josdmyer@ubuntu:~/hack.chat$ sudo npm start

> hack.chat@1.0.0 start /home/josdmyer/hack.chat
> node server.js

/home/josdmyer/hack.chat/server.js:60
for (var client of server.clients) {
                ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by ghost** [comment]
Is there any particular reason behind `sudo`ing `npm`?

**Comment by M4GNV5** [comment]
i dont think thats the problem but try starting it with `node server.js` ?

**Comment by ghost** [comment]
Also, please post the output of `node -v`

**Comment by josdmyer** [comment]
no i just figured i had to sudo

**Comment by josdmyer** [comment]
I have tried node server.js and it gives me the same thing

$ node -v

v0.10.25

**Comment by ghost** [comment]
Have you tried manually applying the fix from `nodejs-legacy`? http://stackoverflow.com/a/21168305/667143

**Comment by josdmyer** [comment]
I screwed something up.  I hadn't tried the fix.  I went ahead and tried it
so it said the file didn't exist so I sudo apt-get install node and now
something isn't right so I'll create a new vm tonight and try again

**Comment by josdmyer** [comment]
when I create my new vm I need to install the following
git, node, nodejs, nodejs-legacy, npm, build-essential libssl-dev

is there anything else I need to install?

**Comment by AndrewBelt** [comment]
node 0.12 is required for the ES6 syntax used in the server. I'd actually recommend using the binary provided from Node's website, since Debian's and Ubuntu's are really old. Or install node from the backports repo.

**Comment by josdmyer** [comment]
the server seems to be up and working now, but the client is giving me
issues

npm install -g less jade http-server

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/jade'

npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/jade']

npm ERR!   errno: 3,

npm ERR!   code: 'EACCES',

npm ERR!   path: '/usr/lib/node_modules/jade',

npm ERR!   fstream_type: 'Directory',

npm ERR!   fstream_path: '/usr/lib/node_modules/jade',

npm ERR!   fstream_class: 'DirWriter',

npm ERR!   fstream_stack:

npm ERR!    [
'/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',

npm ERR!
'/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',

npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }

npm ERR!

npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-57-generic

npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "less"
"jade" "http-server"

npm ERR! cwd /home/josdmyer/hack.chat/client

npm ERR! node -v v0.10.40

npm ERR! npm -v 1.4.28

npm ERR! path /usr/lib/node_modules/jade

npm ERR! fstream_path /usr/lib/node_modules/jade

npm ERR! fstream_type Directory

npm ERR! fstream_class DirWriter

npm ERR! code EACCES

npm ERR! errno 3

npm ERR! stack Error: EACCES, mkdir '/usr/lib/node_modules/jade'

npm ERR! fstream_stack
/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23

npm ERR! fstream_stack
/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53

npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/http-server'

npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/http-server']

npm ERR!   errno: 3,

npm ERR!   code: 'EACCES',

npm ERR!   path: '/usr/lib/node_modules/http-server',

npm ERR!   fstream_type: 'Directory',

npm ERR!   fstream_path: '/usr/lib/node_modules/http-server',

npm ERR!   fstream_class: 'DirWriter',

npm ERR!   fstream_stack:

npm ERR!    [
'/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',

npm ERR!
'/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',

npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }

npm ERR!

npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-57-generic

npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "less"
"jade" "http-server"

npm ERR! cwd /home/josdmyer/hack.chat/client

npm ERR! node -v v0.10.40

npm ERR! npm -v 1.4.28

npm ERR! path /usr/lib/node_modules/http-server

npm ERR! fstream_path /usr/lib/node_modules/http-server

npm ERR! fstream_type Directory

npm ERR! fstream_class DirWriter

npm ERR! code EACCES

npm ERR! errno 3

npm ERR! stack Error: EACCES, mkdir '/usr/lib/node_modules/http-server'

npm ERR! fstream_stack
/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23

npm ERR! fstream_stack
/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53

npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/less'

npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/less']

npm ERR!   errno: 3,

npm ERR!   code: 'EACCES',

npm ERR!   path: '/usr/lib/node_modules/less',

npm ERR!   fstream_type: 'Directory',

npm ERR!   fstream_path: '/usr/lib/node_modules/less',

npm ERR!   fstream_class: 'DirWriter',

npm ERR!   fstream_stack:

npm ERR!    [
'/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',

npm ERR!
'/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',

npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }

npm ERR!

npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-57-generic

npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "less"
"jade" "http-server"

npm ERR! cwd /home/josdmyer/hack.chat/client

npm ERR! node -v v0.10.40

npm ERR! npm -v 1.4.28

npm ERR! path /usr/lib/node_modules/less

npm ERR! fstream_path /usr/lib/node_modules/less

npm ERR! fstream_type Directory

npm ERR! fstream_class DirWriter

npm ERR! code EACCES

npm ERR! errno 3

npm ERR! stack Error: EACCES, mkdir '/usr/lib/node_modules/less'

npm ERR! fstream_stack
/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23

npm ERR! fstream_stack
/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53

npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)

npm ERR!

npm ERR! Additional logging details can be found in:

npm ERR!     /home/josdmyer/hack.chat/client/npm-debug.log

npm ERR! not ok code 0

**Comment by josdmyer** [comment]
it looks like I got it to work now, but I try to go to ip:6060 and I get
not implemented on it

**Comment by AndrewBelt** [comment]
That's the websocket URL. You need to go to the path you are serving the static client files from.

**Comment by josdmyer** [comment]
Sorry a little confused here.

This is the path I have

/home/josdmyer/hack.chat/client

and ip is 10.1.1.173

so do I do 10.1.1.173:6060/home/josdmyer/hack.chat?

**Comment by AndrewBelt** [comment]
Here are the relevant instructions from the README.

```
http-server
```

Change the "frontpage" text in client.js to your liking, and go to http://127.0.0.1:8080.

Are you serving the static files with http-server? It uses port 8080 by default.

**Comment by josdmyer** [comment]
yea I got that part working.  Sorry thought there was an admin section due
to the config file.

**Comment by josdmyer** [comment]
So what is the purpose of an admin username and password in the config.json
file?

**Comment by ghost** [comment]
It's a little bit strangely worded, but if you enter the 'password' as your nick on the hack.chat app, you will be logged in using the 'admin' nickname. It is impossible to use the admin nick without the password.

**Comment by josdmyer** [comment]
ah okay that makes sense now was thinking there was an admin setting
section that you had to go to to use the username and password.

**Comment by kamakazikamikaze** [comment]
I'll just add a direct link that instructs how to install Node v.0.12.x for those who may create more problems or are stuck. This is the easiest way by far. Note that I did install `nodejs-legacy` (which removed `node`) so it may have already pre-made a symlink. [Here's the blog post from Node|Source](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories)

**Comment by neocronx** [comment]
I got the server running, how do I go into the client side and see it for myself? I put the folder in www directory via nginx and it's not working. Any ideas?

EDIT: nevermind.
