### ISSUE TITLE
Client Makefile Line 15 - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wangoland** [AndrewBelt/hack.chat#49]
When trying to make the client version with the 'MAKE' command, the following error appears:

```
$ make
jade index.jade
Makefile:15: recipe for target 'index.html' failed
make: *** [index.html] Segmentation fault (core dumped)
```

**Comment by AndrewBelt** [comment]
Nothing on Node should segfault, unless there's bug upstream. Check your node version, and see if the issue has been fixed (as it likely has) by upgrading your package.
