### ISSUE TITLE
Rename, and other things like that

### ISSUE THREAD

**Issue by feliwyn** [AndrewBelt/hack.chat#5]
Maybe possibility to rename without refresh the page?

**Comment by AndrewBelt** [comment]
A page refresh is a pretty simple way to rename your nickname, otherwise it would cause identity confusion. An announcement like "relogging as feliwyn2" before a refresh would probably be sufficient in a conversation.

**Comment by feliwyn** [comment]
Yeah, but the history?

**Comment by FouadWahabi** [comment]
@feliwyn there's no history in Hack.Chat nothing you say is saved on a server !!
