### ISSUE TITLE
Debian 8 installation issue!

### ISSUE THREAD

**Issue by ZEROF** [AndrewBelt/hack.chat#51]
First of all, nice project.

Debian (8) users need to install node, git and npm before starting. Server side instruction are good, just use node server.js. Issue comes with client setting.

Error after running make:

mkdir -p schemes
lessc --global-var='name=atelier-lakeside' scheme.less > schemes/atelier-lakeside.css
Makefile:8: recipe for target 'schemes/atelier-lakeside.css' failed
make: **\* [schemes/atelier-lakeside.css] Error 1

Have a nice day.

**Comment by AndrewBelt** [comment]
Do you know why lessc fails on your machine? Could you run it in verbose mode?

**Comment by M4GNV5** [comment]
works fine for me (debian 8 too but maybe an older patch? havent updated since intial release :grin:)

**Comment by ZEROF** [comment]
npm start gives this:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart hack.chat@1.0.0
6 info start hack.chat@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info hack.chat@1.0.0 Failed to exec start script
9 error hack.chat@1.0.0 start: `node server.js`
9 error Exit status 8
10 error Failed at the hack.chat@1.0.0 start script.
10 error This is most likely a problem with the hack.chat package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node server.js
10 error You can get their info via:
10 error     npm owner ls hack.chat
10 error There is likely additional logging output above.
11 error System Linux 2.6.32-042stab108.5
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /opt/hack.chat
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

Even when i install nodejs-legacy. This issue could be fixed with ln -s /usr/bin/nodejs /usr/bin/node, but it's better to install package who will do this for us.

**Comment by ZEROF** [comment]
Started from 0. Server side crash. Client make and http-server start working now.

Issue in this moment.

Server side (npm start):

http://paste.debian.net/hidden/93d9f4cc/

Provided logs:

http://paste.debian.net/hidden/25a2b387/

**Comment by AndrewBelt** [comment]
Node v0.12 is required to run the server. I've added that message to the README.
