### ISSUE TITLE
the admin (you) should have a unique tripcode

### ISSUE THREAD

**Issue by M4GNV5** [AndrewBelt/hack.chat#55]
the admin could have like a tripcode saying "admin" in clear text or something like that

**Comment by kipukun** [comment]
Why not just a bold highlight? That would keep it simple and clear.

**Comment by AndrewBelt** [comment]
Perhaps, but isn't red enough?

**Comment by kipukun** [comment]
Is it red already? Then that works fine. No need for unnecessary text.
