### ISSUE TITLE
Not working through proxy

### ISSUE THREAD

**Issue by aksharvarma** [AndrewBelt/hack.chat#56]
While trying to use hack.chat from behind a proxy I couldn't see any prompt for the nick and was unable to use the site at all. I tried changing browsers without success; Google Chrome, Mozilla Firefox and even Conkeror failed. Surprisingly, on Android I was able to get it working from both Chrome and Firefox browsers. I have no idea how that worked, the Android device was connected to the same Wi-Fi.

On checking the Javascript console on Chrome, I found this error.
**WebSocket connection to 'wss://hack.chat/chat-ws' failed: Error in connection establishment: net::ERR_PROXY_CONNECTION_FAILED**

I searched a bit and found that there is some problem with WebSocket working with proxies.

**Comment by AndrewBelt** [comment]
It is entirely up to the proxy to allow or disallow WebSockets. Although, it's attempting to connect to port 443, and starts by creating a TLS session, and then switches protocols from HTTP to sockets, so I don't see how a proxy would be able to distinguish between a WSS and HTTPS connection.
