### ISSUE TITLE
Startup issues

### ISSUE THREAD

**Issue by ravensorrow** [AndrewBelt/hack.chat#57]
I've upgraded nodejs to v.0.12.7, the server started once and then it wouldn't a second time, this is the error(s) it produced (this time);

ubuntu@ip-172-31-0-10:/usr/share/nginx/xaerolimit.net/hack.chat$ npm start

> hack.chat@1.0.0 start /usr/share/nginx/xaerolimit.net/hack.chat
> node server.js

Loaded config.json
Started server on 54.152.16.73:6060
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! hack.chat@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hack.chat@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the hack.chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls hack.chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/nginx/xaerolimit.net/hack.chat/npm-debug.log
ubuntu@ip-172-31-0-10:/usr/share/nginx/xaerolimit.net/hack.chat$ npm owner ls hack.chat
npm ERR! owner ls Couldn't get owner data hack.chat
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "hack.chat"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E404

npm ERR! 404 Not Found: hack.chat
npm ERR! 404
npm ERR! 404 'hack.chat' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/nginx/xaerolimit.net/hack.chat/npm-debug.log
ubuntu@ip-172-31-0-10:/usr/share/nginx/xaerolimit.net/hack.chat$

**Comment by AndrewBelt** [comment]
`EADDRNOTAVAIL` means that the port you've requested is already taken by a process on your machine, likely by the first hack.chat process. If you killed the first process in a nasty way (e.g. `kill -9`), the server will not free the port, until Linux times it out for you in 60 seconds. If it still gives you trouble, you probably still have the first server running in the background.

**Comment by ravensorrow** [comment]
OK, got all that squared away and my firewall updated. I can connect, but I can't type anything. I can see the text box, and type in it, the sidebar works, just can't see what I type or users in the channel...

![image](https://cloud.githubusercontent.com/assets/3761618/8898232/fe82931e-33ee-11e5-911d-c5839a737d81.png)

**Comment by AndrewBelt** [comment]
It looks like the web client can't connect to the WebSocket server. There could be a number of reasons for this. First, can you `curl localhost:6060` (assuming it's hosted on the same machine) to get "Not implemented"?

**Comment by ravensorrow** [comment]
ubuntu@ip-172-31-0-10:~/.npm/http-server/0.8.0$ curl localhost:6060
Not implemented
ubuntu@ip-172-31-0-10:~/.npm/http-server/0.8.0$

I had to insert a line break after implemented.

**Comment by AndrewBelt** [comment]
Okay, looks like it can connect just fine. Open the web console and refresh the page. What error message do you get?

**Comment by ravensorrow** [comment]
HA! I forgot to open 6060 too! Once I did, it worked.

**Comment by AndrewBelt** [comment]
Great!
