### ISSUE TITLE
hack.chat is encrypted?

### ISSUE THREAD

**Issue by neocronx** [AndrewBelt/hack.chat#59]
Hello: I just want to know if hack.chat software is encrypted? I don't see it via FAQ or README. Let me know.

**Comment by M4GNV5** [comment]
its using `wss` so afaik it should be encrypted

**Comment by neocronx** [comment]
Ok, thanks.

**Comment by AndrewBelt** [comment]
Yes, the lock in your address bar (in the absense of a warning sign) shows that the connection, including all messages sent/received, are over a secure connection until they reach the hack.chat server and are parsed.

**Comment by AndrewBelt** [comment]
I should mention though that the hack.chat software hosted from this git repo does not have encryption by default. You have to configure your web server (Nginx in the case of https://hack.chat/) to serve static files and route a Websocket connection over HTTPS/WSS.
