### ISSUE TITLE
hack.chat on TOR?

### ISSUE THREAD

**Issue by neocronx** [AndrewBelt/hack.chat#60]
Hello.. I managed to get everything all 'n running via ngnix server. I am trying to figure out how to get it hosted on TOR. I know how to host website via nginx, but how do I configure hack.chat via .onion on TOR? Thanks!

**Comment by AndrewBelt** [comment]
To be honest, I have no idea. I've never used Tor, so I don't know how networking should be configured. Hack.chat is no different than other web servers though, so there's probably a tutorial for forwarding ports through it somewhere online.
