### ISSUE TITLE
Client cant connect to server

### ISSUE THREAD

**Issue by 112RG** [AndrewBelt/hack.chat#67]
i am trying to set this up locally i have the server on  0.0.0.0:6000 and the client on 0.0.0.0:8080 but when i open a channel on the client it loads and just stays there without showing the nickname window

**Comment by AndrewBelt** [comment]
The default server port is 6060. Did you change that in client.js?

**Comment by 112RG** [comment]
i repulled the repo at setup and i got this Started server on 0.0.0.0:6060

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by AndrewBelt** [comment]
You must have another program claiming port 6060. (Hence the EADDRINUSE).

**Comment by 112RG** [comment]
do i just change the port on both server and client and do i run the server and client on the same machine

**Comment by AndrewBelt** [comment]
Whatever port you chose, the WebSocket address in client.js has to match the port of the server. You could run the server and client on the same or different machines, your choice.

**Comment by 112RG** [comment]
okay my server is running on 127.0.0.1:8080 and its loaded with no errors and my client is running on http://0.0.0.0:8080 but when i load the client url it loads and when i click a room it loads it and then just does nothing 

this is the log from the client 

Starting up http-server, serving ./ on: http://0.0.0.0:8080
Hit CTRL-C to stop the server
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /style.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /katex/katex.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /schemes/atelier-dune.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /katex/katex.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /katex/contrib/auto-render.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /client.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /schemes/default.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /katex/fonts/KaTeX_Main-Regular.woff2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /katex/fonts/KaTeX_Math-Italic.woff2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /katex/fonts/KaTeX_Size2-Regular.woff2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:06 GMT] "GET /favicon.ico" Error (404): "Not found"
[Thu, 13 Aug 2015 09:08:08 GMT] "GET /?meta" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:08:59 GMT] "GET /?meta" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[Thu, 13 Aug 2015 09:10:09 GMT] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"

**Comment by M4GNV5** [comment]
you also need to start the `server.js` using `node server.js`

**Comment by 112RG** [comment]
i have i changed the port and now when i click a channel it says not implemented yet

**Comment by 112RG** [comment]
i got it working it was just the order i started them in thank this program is great

**Comment by 112RG** [comment]
one more thing how do i log in as admin

**Comment by AndrewBelt** [comment]
Let your nickname be `admin#password` where admin and password are the values set in config.json.

I should really put that info into the README.

**Comment by 112RG** [comment]
one more thing how do i change the ip of the http server

**Comment by AndrewBelt** [comment]
I don't understand your question. Your IP is determined by the machine you are hosting the server from.

**Comment by 112RG** [comment]
when i start the http server for the client the default ip os 0.0.0.0 and the servers ip is 0.0.0.0 how do i change the client and server ip and do they have to be the same

**Comment by AndrewBelt** [comment]
Those are binding IPs. If the servers are hosted from the same machine, they have the same IP address.
