### ISSUE TITLE
Add HSTS header

### ISSUE THREAD

**Issue by lucaswerkmeister** [AndrewBelt/hack.chat#7]
The HTTP version of the site redirects to HTTPS via 301 Moved Permanently, but if someone visits http://hack.chat/?my_secret_channel, that channel’s name is still compromised since it is transmitted before the switch to an encrypted connection can happen. The server should send an HSTS header to avoid this if the user agent visited hack.chat in the past.

**Comment by AndrewBelt** [comment]
Thanks! Added HSTS header to webserver.

**Comment by lucaswerkmeister** [comment]
Great, thanks!
