### ISSUE TITLE
Empty line prevention

### ISSUE THREAD

**Issue by ToastyStoemp** [AndrewBelt/hack.chat#93]
Using multiple dollar signs it's still possible to make a blank message, often used for flooding the chat.
https://github.com/AndrewBelt/hack.chat/blob/master/client/client.js#L190

**Comment by AndrewBelt** [comment]
A complete solution would be arbitrarily complicated since you can insert many unprintables in LaTeX. And it doesn't solve the direct problem of flooding the chat. You don't need a blank message to do that.
